### ISSUE TITLE
Apple M1 support

### ISSUE THREAD

**Issue by dustin** [caldwell/build-emacs#104]
The latest builds are working fine for me under emulation, but I'm hoping it is going to be possible to run natively on the new Macs someday soon.

**Comment by jdortiz** [comment]
I never got 27.1+ to run in the DTK. @dustin Are you running yours successfully from the Finder?

**Comment by dustin** [comment]
I'm running a nightly I downloaded.  Have you activated rosetta?

**Comment by jdortiz** [comment]
I believe the issue is that the architecture is amd64 and it cannot find the proper binary and directories.

**Comment by thynus** [comment]
Universal Binary available on emacsformacosx.com 

> I believe the issue is that the architecture is amd64 and it cannot find the proper binary and directories.

the m1 is arm64

**Comment by thynus** [comment]
See:
https://github.com/caldwell/build-emacs/issues/103#issuecomment-822056419

m1 native builds work great on m1 macs!

**Comment by caldwell** [comment]
M1 support has been in since late January/early February 2021. The current 27.2-2 release has an arm64 binary.
