### ISSUE TITLE
Error `"This application will not run on your computer. Sorry!"`with Emacs-27.2-3-universal.dmg on macOS 11.6

### ISSUE THREAD

**Issue by erikmd** [caldwell/build-emacs#113]
Hi, I've installed Emacs [using Homebrew cask](https://formulae.brew.sh/cask/emacs) on my MacBook Air:
```
brew install --cask emacs
```
which automatically downloaded https://emacsformacosx.com/download/emacs-builds/Emacs-27.2-3-universal.dmg

Then, I workarounded #109 by running
```
xattr -d -r com.apple.quarantine /Applications/Emacs.app
```

But on next run from a regular zsh terminal:
```
emacs
```
I get "This application will not run on your computer. Sorry!"

FTR, `emacs` is a symlink to `/opt/homebrew/bin/emacs` which in turn points to the ruby script `/Applications/Emacs.app/Contents/MacOS/Emacs`

so I believe the issue directly comes from this script, because I can both run:

* `/Applications/Emacs.app/Contents/MacOS/Emacs-arm64-12`
* `/Applications/Emacs.app/Contents/MacOS/Emacs-x86_64-10_11`

with no error.

Unfortunately I'm not a ruby developer so I've no clue about how to debug `/Applications/Emacs.app/Contents/MacOS/Emacs`

Can you help me?

My system:
```
% sw_vers
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165

% uname -mrs 
Darwin 20.6.0 arm64
```

**Comment by caldwell** [comment]
This should be fixed in tomorrow's Nightly build, 2022-04-06.
