### ISSUE TITLE
Hangs starting up Monterey 12.5

### ISSUE THREAD

**Issue by BarrySmith** [caldwell/build-emacs#122]
Been a user for a long time. Great stuff

Just installed 28.1. When I double click on Emacs.app the Emacs logo in the Dock just bounces forever. Looking in the activity monitor  I get the following (screenshot)

![Untitled](https://user-images.githubusercontent.com/512185/183313475-1e2ae81e-7570-4f76-9340-cbb6e4396854.jpg)

If I go into the Emacs.app directory and double click Emacs or one of the Emacs Intel versions, a terminal starts up and then Emacs, leaving the very annoying terminal hanging around but seems to work.

I have the same permissions for full disk access for Emacs (and Ruby) I have had for a long time.

**Comment by rnikoopour** [comment]
I had this same issue.  In my startup I was spawning an SSH agent.

Once I commented that line out it booted up regularly.

**Comment by caldwell** [comment]
That should be ok as long as you only launch it during interactive mode. I use this to test in bash:

```sh
if [[ "$-" =~ i ]]; then
    # Interactive stuff
fi
```

I don't know zsh enough to write the equivalent.

**Comment by BarrySmith** [comment]
> 

Great. It was also an ssh-agent startup that was causing the hang. Had that for years, it didn't cause problems with the previous launcher.

**Comment by BarrySmith** [comment]
Working for me with fix as listed above.
