### ISSUE TITLE
emacs-nox binary to avoid need for -nw flag?

### ISSUE THREAD

**Issue by SaraCPickett** [caldwell/build-emacs#129]
I use emacs exclusively from the command line and I want it to stay in Terminal rather than launching its own window, so I run it with the -nw flag, but that requires remembering to use the flag or setting up an alias.
Years ago I used to use emacs-nox, which avoided using X.  It might be too confusing to reuse the command name, but I wish there was a binary for macos that automatically ran emacs with -nw.  I think it could be done with a little binary in bin that runs the main Emacs rust launcher with the -nw flag.
Thanks.

**Comment by caldwell** [comment]
That's not a terrible idea. It could probably just be a shell script in the app bundle. How about just `emacs-nw`? It could probably be as simple as
```
#!/bin/sh
${0%/*}/emacs -nw "$@"
```

**Comment by caldwell** [comment]
The [Nightly build for 2023-02-09](https://emacsformacosx.com/emacs-builds/Emacs-2023-02-09_04-02-50-1518fc5d7c5bedbbe35053696c7ec06020c81b05-universal.dmg) has this file in there. It will eventually make it into a release (which is soonish if I understand correctly (on the order of months).
Thanks for the idea.
