### ISSUE TITLE
Missing launch folder

### ISSUE THREAD

**Issue by apj68** [caldwell/build-emacs#132]
I'm building on MacOS 10.14.6 which is as high as my hardware takes me.  For some reason none of the other Emacs builds work for me but for the past couple of builds (25 and 27) I've been able to use your builder to successfully build.  Currently, however, I don't get a `launch` folder so the `combine-and-package` step fails.

Hope you can provide some tips on troubleshooting!

**Comment by caldwell** [comment]
You need to run `make` in the build-emacs directory to compile the rust launcher (you also need the rust compiler installed). That tries to build a fat binary (arm, x86_64). If that isn't working for whatever reason then you can build a non-fat binary:
```shell
cargo build --release && cp target/release/launch .
```
That will build it and stick it in the project root where the combine-and-package program expects it.

**Comment by apj68** [comment]
That worked, thanks for your help!
