### ISSUE TITLE
invalid certificate on https://emacsformacosx.com/

### ISSUE THREAD

**Issue by ryepup** [caldwell/build-emacs#138]
Not sure if this is the right place to report it, but the cert on https://emacsformacosx.com/ has expired, and commands like `brew install --cask emacs` are failing with errors like `curl: (60) SSL certificate problem: certificate has expired`

**Comment by caldwell** [comment]
Thanks, this is a fine place to report that (it's not really directly related to the builds, but it's definitely indirectly related and there's no other place to report short of directly emailing me).

Our hosting provider got stuck for some reason (they were recently hassling us for the builds using up a lot of disk space—I'm not sure if this is related to that). I manually killed the cert and then re-enabled TLS support and it seems to be working now.

Thanks for the heads up.
