### ISSUE TITLE
support GnuTLS opportunistically

### ISSUE THREAD

**Issue by tzz** [caldwell/build-emacs#25]
It would be nice if, like in Windows, the GnuTLS libraries were opportunistically used on OS X or if they were bundled with the binary.

@caldwell I think I brought this up in private e-mail a while ago but can't find it.  Well, if I can help make this happen, please let me know.  I personally use GnuTLS from Homebrew and compile my own Emacs because this build script doesn't support it, but would love to switch to a more integrated binary that I can test both as an Emacs developer and a user.

**Comment by lunaryorn** [comment]
@caldwell I'd love to see GNUTLS support as well.  Can you point me to a place, where I could start to implement it?

**Comment by rakkesh** [comment]
@lunaryorn check out http://github.com/renard/emacs-build-macosx for building a self contained Emacs.app for Mac OS X with additional goodies - gnutls, libxml2, and etc.

**Comment by lunaryorn** [comment]
@rakkesh I'm not sure what this repository adds over a simple `brew install emacs`, and it does apparently not provide binary packages—which is all that this repo is about.

**Comment by rakkesh** [comment]
The script does generate a binary package (dmg). Refer to the [script](https://github.com/renard/emacs-build-macosx/blob/1895b288810ee45457c7a18c982e5da3cc25a192/build-emacs). I use this script to generate and distribute `Emacs.app` within a local group of emacs enthusiasts.

I had mentioned this [link](https://github.com/renard/emacs-build-macosx) here to help out with @caldwell's [comment](https://github.com/caldwell/build-emacs/issues/1#issuecomment-1582349) on installing external libraries in to app bundle which can then be distributed on emacsformacosx.com.

**Comment by heikkil** [comment]
A number of emacs users have been having serious problems running links to https sites, especially from elfeed (https://github.com/skeeto/elfeed/issues/39). The solution seems to be to compile emacs with `--with-gnutls`. As long as emacsformacosx, does not include it, I can not use it.

**Comment by lunaryorn** [comment]
@caldwell I presume that the infrastructure to include additional libraries in the build now exists?  Would you mind to take another look at #1 and #37 now?  It'd be great to have this libraries in the Emacs build.

I wouldn't mind doing a pull request, but I'd appreciate a hint or two about where to look and what to watch out for.

**Comment by caldwell** [comment]
@lunaryorn Yes (see ad407754d393cee75c1d13f4b0e74c2436304fbf, f24bd2bd88f248b544ef25a9aa3ca770a561804f). It uses Homebrew to compile binaries (and collect source code). I have local changes for ImageMagick (#1) and librsvg (#37). Librsvg should actually be pretty easy and I might just push that. I got stuck on ImageMagick because it's not a simple library. It has a plugin system of its own and I haven't figured out how to subvert it so that it looks for its plugins in a relative path. And it's set up so *everything* is a plugin—if it can't load them then you can't even open jpegs or pngs.

**Comment by lunaryorn** [comment]
@caldwell Thanks a lot of for the status update ❤️
