### ISSUE TITLE
Crash on 10.5.8 PPC

### ISSUE THREAD

**Issue by AKielhorn** [caldwell/build-emacs#33]
I'm trying to use Emacs 24.4 (2014-10-20) on my Powerbook.

When I start Emacs I get a

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[EmacsImage drawInRect:fromRect:operation:fraction:respectFlipped:hints:]: unrecognized selector sent to instance 0x7229970'

Thread 0 Crashed:
0   libSystem.B.dylib             	0x903589f0 __kill + 12
1   Emacs-powerpc-10_4            	0x000a6d70 terminate_due_to_signal + 176
2   Emacs-powerpc-10_4            	0x000c55c4 emacs_abort + 20
3   Emacs-powerpc-10_4            	0x00199fec ns_term_shutdown + 156
4   Emacs-powerpc-10_4            	0x000a5a14 shut_down_emacs + 324
5   Emacs-powerpc-10_4            	0x000a6d40 terminate_due_to_signal + 128
6   Emacs-powerpc-10_4            	0x000c56b0 handle_fatal_signal + 16
7   Emacs-powerpc-10_4            	0x000c5b80 deliver_fatal_thread_signal + 144

Axel

**Comment by caldwell** [comment]
This looks like an Emacs problem, and not a build issue. Emacs has dropped PPC support in the latest nightlies, though 24.1 should work on PPC.
