### ISSUE TITLE
Open new files in same window

### ISSUE THREAD

**Issue by luisgerhorst** [caldwell/build-emacs#38]
I set up `emacsclient` as described on the [website](http://emacsformacosx.com/tips), when I now open a new file either by using the Finder or by the Terminal I always get a new (Mac OS X) window. How can I open files in the existing window that Emacs created on startup?

**Comment by caldwell** [comment]
Try `M-x customize-variable RET ns-pop-up-frames`. That sounds like the setting you want to change.

**Comment by luisgerhorst** [comment]
@caldwell Thank's, that's what I wanted.

I anyway still have the problem that when I open a file from one Desktop while Emacs is in another one it does't switch to the Desktop where Emacs is open. I only see "Emacs" in the menu bar. I have "When switching to an application, switch to a Space with open windows for the application" enabled in System Preferences > Mission Control.

**Comment by caldwell** [comment]
`x-focus-frame` is the function that you probably want, though calling it at the right time is a little tricky.

I had a similar issue with opening new frames, and this is how I solved it:
```elisp
(defadvice server-create-window-system-frame (after server-create-window-system-frame-and-focus)
  "Wrapper that opens the frame from emacsclient and then focuses it"
  (when (not ad-return-value)
    (x-focus-frame ad-return-value)))
(ad-activate 'server-create-window-system-frame)
```
That uses Emacs 'advice' mechanism to wrap a function with another function. Monkeypatching, basically. In my example, I'm patching the function called `server-create-window-system-frame`. My 'advice' is named `server-create-window-system-frame-and-focus` and is called *after* the original function runs. I'm not exactly sure which function you'd need to patch, but `ns-handle-nxopen` sounds promising.

Here are the [docs for emacs advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html). It looks like the code example I gave is now considered obsolete and there's new functions to do the same thing.

**Comment by luisgerhorst** [comment]
Thanks for the answer. I ended up adding

```elisp
(defun activate-emacs (FILENAME &optional WILDCARDS)
  (do-applescript "tell application \"Emacs\" to activate"))
(advice-add 'find-file :after #'activate-emacs)
```

but it still does't switch to the desktop where Emacs is open. Using `(x-focus-frame nil)` instead of AppleScript also doesn't help. I tried `ns-handle-nxopen` instead of `find-file` as you suggested but it looks like it does not even get called when I open a file using the Finder (wonder why).

**Comment by caldwell** [comment]
I think anything more here would be an actual Emacs bug, so I'm going to close this.
