### ISSUE TITLE
Auto start Emacs after OSX login, makes Emacs hang

### ISSUE THREAD

**Issue by hansbogert** [caldwell/build-emacs#42]
When Emacs is active when logging of or restarting, and OSX is logging in again Emacs hangs, using 100% CPU. I've tested this with clean .emacs{,.d}

Used the Macports version on Mavericks, if this is not the place to report this or more info is needed, please let me know.

**Comment by cg433n** [comment]
I'm noticing this behavior, too.
Emacs 24.4, OSX 10.10.4

**Comment by caldwell** [comment]
This happens to me too. This isn't the right place to report it though—this project is only for the build scripts that emacsformaosx.com uses. The main Emacs bug reporter is the right place for this, I believe. `M-x report-emacs-bug` is the canonical way to report bugs to the Emacs developers (it basically just creates a correctly formatted email report to bug-gnu-emacs@gnu.org).

I just checked at it appears this has already been reported in [Emacs Bug 19879](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=19879). You add comments to the bug by email (instructions are on the page).
