### ISSUE TITLE
Update icon for Yosemite

### ISSUE THREAD

**Issue by cg433n** [caldwell/build-emacs#43]
I've created an icon for Emacs which matches the appearance of OS X Yosemite.
(https://github.com/cg433n/emacs-yosemite-icon)

Is there any way to include it in the build process?

**Comment by caldwell** [comment]
Sure. I already include an alternate icon in the "More…" directory. But I'd need you to explicitly release it under the GPL (correct me if I'm wrong, but I don't see a license anywhere in your repo).

**Comment by cg433n** [comment]
I licensed the repo under GPL.

**Comment by caldwell** [comment]
Thanks. It's along with the other alternate icon in the "More" Folder and should appear starting in tonight's nightly.
