### ISSUE TITLE
Running emacs with -nw from terminal

### ISSUE THREAD

**Issue by ekstroem** [caldwell/build-emacs#44]
Hi all,

Apologies if this is not an emacsforosx issue (and I don't think it is but more like an OS X issue) but here's my problem:

I run most stuff in terminals. For the emacs version that I have with Maverick (version 22) I can just run emacs in a terminal and runs `/usr/bin/emacs` and doesn't start a new window (ie., like having an `-nw' argument).

Now I've installed the latest version of emacsforosx and the app runs nicely. However, I'd really like to use that version from my terminals. If I run `/Applications/Emacs.app/Contents/MacOS/Emacs -nw` then all is fine and dandy.

However, if I would like to fire up a file `/Applications/Emacs.app/Contents/MacOS/Emacs -nw test` then the emacs app looks for the file in my home directory regardless of where I'm currently at. If I run the same command without the `-nw` argument I get the same result except that a new emacs window is started.

I tried to make an alias

```
alias eee= open -a /Applications/Emacs.app/Contents/MacOS/Emacs -nw
``` 
but that throws an error and 
```
alias eee= open -a /Applications/Emacs.app/Contents/MacOS/Emacs
``` 
finds the file in the current directory when I use it but starts an emacs window.

Is there a command line version I can call instead of the app?

**Comment by caldwell** [comment]
If you want to pass args to a program with "open" then you need to use the `--args` flag:

    alias eee= open -a /Applications/Emacs.app/Contents/MacOS/Emacs --args -nw

But I'm wondering why use open at all? Why not just:

    alias eee=/Applications/Emacs.app/Contents/MacOS/Emacs -nw

?

**Comment by ekstroem** [comment]
I tried both solutions but with different results. The first
```
/Applications/Emacs.app/Contents/MacOS/Emacs -nw myfile
```
opens up `myfile` in the home directory and not in the current directory.

The other solution with `open` (and I'd really prefer a solution that does not involve the use of `open`) throws an error
```
$ open -a /Applications/Emacs.app/Contents/MacOS/Emacs myfile --args -nw
LSOpenURLsWithRole() failed for the application /Applications/Emacs.app/Contents/MacOS/Emacs with error -10810 for the file /Users/ekstroem/bin/myfile.
```

**Comment by caldwell** [comment]
>     /Applications/Emacs.app/Contents/MacOS/Emacs -nw myfile
>
> opens up myfile in the home directory and not in the current directory.

Let me make sure I understand what you are saying. if I do:

    echo hi > /tmp/hi
    cd /tmp
    /Applications/Emacs.app/Contents/MacOS/Emacs -nw hi

I definitely get the "hi" file in /tmp. Are you saying you get a new empty "hi" file in your home dir?

If so, it might be a problem with your .emacs file. Try:

     /Applications/Emacs.app/Contents/MacOS/Emacs -Q -nw hi

…which takes your .emacs out of the picture.

**Comment by ekstroem** [comment]
Ah!

I had checked various locations for the .emacs file but it turned out that a stray
```
(setq command-line-default-directory "~/")
```
had snuck into the `site-start-el` file. &#€"# That took me quite some pondering.

Thanks and sorry for bugging people here - it wasn't an emacsforosx problem.
