### ISSUE TITLE
vc-dir in Emacs 24.5.1 doesn't work with git (assumes svn)

### ISSUE THREAD

**Issue by jamshid** [caldwell/build-emacs#45]
Hi, not sure if this is a regression from previous emacsforosx.com releases, but the built-in emacs "vc" package doesn't work with git directories.

```
$ /Applications/Emacs.app/Contents/MacOS/Emacs --version
GNU Emacs 24.5.1
$ /Applications/Emacs.app/Contents/MacOS/Emacs -q ~/IdeaProjects/mygitproject/
```

When I run "vc-dir" it doesn't recognize my directory as being git, it seems to assume "svn" then reports an error:

```
svn: E155007: '/Users/.../IdeaProjects/mygitproject' is not a working copy
```

Any idea what might be wrong? I don't see this problem with built-in OS X emacs 22.1, vc-dir works (at least sort of) and displays a message like `No files locked under /Users/.../IdeaProjects/mygitproject/`.

**Comment by caldwell** [comment]
On 8/17/15 1:36 PM, jamshid wrote:
> Any idea what might be wrong? I don't see this problem with built-in OS
> X emacs 22.1, vc-dir works (at least sort of) and displays a message
> like |No files locked under /Users/.../IdeaProjects/mygitproject/|.

My first guess is PATHs, but if you're running from the terminal like
that then it should inherit your paths nicely (running from the Dock or
the Finder inherits their environment which doesn't have any good PATHs
unless you went out of your way and did "launchtl setenv"). Your test
works on my local 24.5.1 install, so I'm not sure.

I don't think this is a build problem with Emacs though, so the best way
forward is probably to use `M-x report-emacs-bug` and get the main Emacs
devs to help you.

-David

**Comment by jamshid** [comment]
Thanks, okay, will go that route. 

I did just find this workaround: if I make `vc` try git *before* svn, things seem to work:

`M-x set-variable vc-handled-backends (Git Svn Hg Mtn Arch)`

Now vc-dir works on git and svn working directories. I guess I could try to debug the issue by looking in /Applications/Emacs.app/Contents/Resources/lisp/vc/vc.el.gz.

**Comment by caldwell** [comment]
Do you per chance handle your dot-files with svn?

**Comment by jamshid** [comment]
Interesting... no, my .emacs and .bashrc are not under any source control. But I do see that I have a /Users/jamshid/.svn/ directory containing a single "config" file with the line `global-ignores = .git`. 

Don't remember what exactly this does or why I created it. 

I guess emacs vc-dir sees the .svn in my home directory so it assumes any subdirectory is managed by svn?
