### ISSUE TITLE
Changing font causes rendering issues

### ISSUE THREAD

**Issue by nylar** [caldwell/build-emacs#47]
![screen shot 2015-12-03 at 14 09 08](https://cloud.githubusercontent.com/assets/7841264/11562707/95b04018-99c7-11e5-8209-3e132e53b027.png)

Emacs for Mac OS X v24.5.1, installed via Homebrew.

Steps to reproduce:

1. Change the font size, either via the Set default font menu item or M-x customize-face.
2. Move up a couple of lines with the directional keys

When the font size changes, it appears to zoom the window, followed by graphical issues when it has to redraw the window.

**Comment by caldwell** [comment]
> Emacs for Mac OS X v24.5.1, installed via Homebrew.

Thanks for the thorough bug report. Unfortunately, this repo is for the build scripts for the binaries at http://emacsformacosx.com. The best way to report this issue is with `M-x report-bug` from within Emacs.
