### ISSUE TITLE
Running under X11 as well as natively?

### ISSUE THREAD

**Issue by haase** [caldwell/build-emacs#49]
I'd like to launch emacs under X11 when I'm ssh'd into the machine and DISPLAY is set correctly (for example, xterm works).  However, it doesn't do so and even when I specify display directly (with -d, as described in the --help message), it just runs in the terminal or pops up on my Mac's screen (depending on which executable I use).  Am I doing something wrong?  Or do I need to build my own version of Emacs with the X11 support as well as the native windowing support?

**Comment by caldwell** [comment]
The Emacs builds currently don't build with X11 support (since Mac OS X doesn't ship with X11 libs). I wouldn't mind including them, but I need to get off my butt and get .app local dylibs working. One day...
