### ISSUE TITLE
bug: closing frame while in fullscreen crashes emacs GUI

### ISSUE THREAD

**Issue by skamsie** [caldwell/build-emacs#50]
Closing frame while in fullscreen crashes emacs GUI. The steps are:

1. open emacs for osx and make it fullscreen
2. make new frame ```ctrl-x 5 2``` '(make-frame-command)'
3. delete frame ```ctrl-x 5 0```

emacs crashes :(

NOTE: only reproduces on fullscreen mode. I have a macbook pro mid 2012 (10.11 (15A284)).

**Comment by caldwell** [comment]
What version of Emacs are you running? I'm unable to duplicate this with [the latest pretest](http://emacsformacosx.com/emacs-builds/Emacs-pretest-25.0.92-universal.dmg). Can you verify that it crashes with that build on your computer?

**Comment by skamsie** [comment]
Nope does not happen with this one. thanks
