### ISSUE TITLE
XWidget support ?

### ISSUE THREAD

**Issue by wh1406** [caldwell/build-emacs#52]
hi there

thanks for your work, have you ever think about to build with XWidget support ? i think it's really cool and useful feature on emacs 25.1 

Thanks

**Comment by ninrod** [comment]
I'm also using your builds and am missing the xwidget support. Please add it!

**Comment by caldwell** [comment]
The XWidget stuff is only available for gtk builds. It is not supported on Cocoa/nextstep (as far as I can tell).
