### ISSUE TITLE
Compile with xwidgets support

### ISSUE THREAD

**Issue by AlexChesters** [caldwell/build-emacs#53]
Running `M-x xwidget-webkit-browse-url` using Emacs 25.1 results in the following error:
```
user-error: Your Emacs was not compiled with xwidgets support
```

It would be good if we were able to compile with xwidgets support.

**Comment by caldwell** [comment]
The XWidget stuff is only available for gtk builds. It is not supported on Cocoa/nextstep (as far as I can tell).
