### ISSUE TITLE
High Sierra Beta 5 : Unable to load color ...

### ISSUE THREAD

**Issue by mariopaumann** [caldwell/build-emacs#65]
Hello !

Just upgraded to High Sierra Beta 5 and now Emacs shows my files black on black.
After removing all .emacs* it's kind of more visible but i see the general cause in *Messages*

Warning: arch-dependent data dir '/Users/build/workspace/Emacs-Multi-Build/label/mavericks/emacs-source/nextstep/Emacs.app/Contents/MacOS/libexec/': No such file or directory
Unable to load color "grey75"
Unable to load color "grey90"
Unable to load color "grey20"
Unable to load color "grey75" [2 times]
Unable to load color "grey95"
Unable to load color "grey90"
Unable to load color "grey20"
Unable to load color "gray60"
Unable to load color "gray80"
Unable to load color "gray40"
For information about GNU Emacs and the GNU system, type C-h C-a.
Unable to load color "grey75"
Unable to load color "RoyalBlue3"
Unable to load color "medium blue"
Mark set

The status row, which seems to use this colors, is completely black.

![bildschirmfoto 2017-08-09 um 12 39 03](https://user-images.githubusercontent.com/10651646/29117767-c0950b8e-7cff-11e7-8452-3a3c076f7172.png)

I googled, and found older similiar problems
the only solution for me now is :

```
rm ~/Library/Colors/Emacs.clr
rm -rf .emacs.d/

```
before starting emacs. Then colors seem ok.
closing (with autosave) and restarting, colors are messed up again.

Starting emacs with my temporary solution :
![bildschirmfoto 2017-08-09 um 12 53 16](https://user-images.githubusercontent.com/10651646/29118349-ecfb04d8-7d01-11e7-8389-6670da6deb9c.png)

Restarting emacs :
![bildschirmfoto 2017-08-09 um 12 53 37](https://user-images.githubusercontent.com/10651646/29118359-f70524e0-7d01-11e7-89ae-e5a0ec10083f.png)

Thank you for your help, Mario

**Comment by mariopaumann** [comment]
- on High Sierra Beta 4 i didn't have this problem
- using brew emacs has exact the same problem

**Comment by caldwell** [comment]
Thanks for the report. If both the Brew version and this version have the issue, then it sounds like a generic Emacs bug and not a bug in the build scripts. You can file a bug in Emacs with `M-x report-emacs-bug`—that will get the report in front of the people that can fix it.

**Comment by mariopaumann** [comment]
But is solved in High Sierra Beta 6 by Apple
