### ISSUE TITLE
Problem with signing of Emacs-pretest-26.0.91-universal.dmg?

### ISSUE THREAD

**Issue by dhull** [caldwell/build-emacs#66]
I downloaded and attempted to run the latest Emacs pretest version. When I opened the app, I get the error: "“Emacs.app” is damaged and can’t be opened. You should move it to the Trash."

I have the "Allow apps downloaded from: App Store and identified developers" option selected in the Security & Privacy system preferences pane.

```shell
$ spctl -a ~/Downloads/Emacs.app
/Users/david.hull/Downloads/Emacs.app: CSSMERR_TP_CERT_EXPIRED

$ codesign -dvv ~/Downloads/Emacs.app
Executable=/Users/david.hull/Downloads/Emacs.app/Contents/MacOS/Emacs
Identifier=org.gnu.Emacs
Format=app bundle with generic
CodeDirectory v=20200 size=205 flags=0x0(none) hashes=1+3 location=embedded
Signature size=8891
Authority=(unavailable)
Info.plist=not bound
TeamIdentifier=5BRAQAFB8B
Sealed Resources version=2 rules=12 files=4017
Internal requirements count=2 size=228
```

**Comment by caldwell** [comment]
Thanks!
Apparently `codesign` doesn't complain when the certificate expires! I renewed everything and built a new pretest that should be code signed correctly. I'm not going to worry about nightlies (you can always right click to open them). New nightlies will be signed with the new key.

[Direct download here](https://emacsformacos.com/emacs-builds/Emacs-pretest-26.0.91-1-universal.dmg).
[Emacs build list here](https://emacsformacos.com/builds).
