### ISSUE TITLE
Emoji 😅

### ISSUE THREAD

**Issue by deybhayden** [caldwell/build-emacs#68]
Hey there,

Thanks so much for providing builds via www.emacsformacosx.com! This project is now being used in [homebrew-cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/emacs.rb) as it provides a traditional Mac app package. I was wondering though, is there any way we could enable emoji support in the binaries as they were [removed somewhat controversially](https://swsnr.de/posts/bye-bye-emojis-emacs-hates-macos).

**Comment by deybhayden** [comment]
I should say I saw a patched version in homebrew - https://github.com/a3ammar/homebrew-emacs-emoji/blob/master/Formula/emacs-emoji.rb - but was hoping to still utilize the cask installation due to more natural Mac behavior (emacs shows up in spotlight, etc)

**Comment by deybhayden** [comment]
I'm going to close this out as I assume this set of scripts is really intent on delivering the "vanilla, no frills" emacs. This [emacs-plus](https://github.com/d12frosted/homebrew-emacs-plus) repo has emoji support. 👍

**Comment by caldwell** [comment]
> "vanilla, no frills" emacs

Yes, exactly that. I find it a much smaller scope and it makes things much easier for me to just deliver Emacs as it is. If I were to start patching it I'd have to take on the support burden, whereas right now I can pass people off to the main Emacs bug reporter with a clean conscience. I agree that the Emoji decision was… Well, it seems weirdly petty to me. But I'm committed to delivering Emacs as the main devs see it, not as I want it.
