### ISSUE TITLE
Emacs 26 regression due to build issue

### ISSUE THREAD

**Issue by wyuenho** [caldwell/build-emacs#71]
There was a really annoying issue with [`read-file-name` reading symlinks](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=28865) on Emacs 26 that was fixed by working around some portability issues with `faccessat` and `fstatat`. The feature detection doesn't seem to work on builds made on 10.9.

I've just tried building on 10.13, and Alan Third has tried on 10.12. The fix works for builds built on both macOS versions. The issue appear to originate between 10.9 and 10.11.

Further details:
- http://lists.gnu.org/archive/html/bug-gnu-emacs/2018-04/msg01068.html
- https://github.com/emacs-mirror/emacs/commit/7775c4729814431608c943643a490ad5f1f68a99

So the question is, since if you continue to support 10.9, none of you builds is going to include that fix and they'll all be broken on recent macOSs, I was wondering what you think the best course of action is to deal with this issue.

**Comment by caldwell** [comment]
I've added a 10.10 build to the package (which will be chosen on all OSes >= 10.10) which fixes this issue. Nightlies starting with [2018-05-19](https://emacsformacos.com/emacs-builds/Emacs-2018-05-19_01-40-13-593c367b0727affc739832ab4f4bdb9d7dd1ddd7-universal.dmg) should have the new 10.10 binary. I also went ahead and rebuilt the [latest pretest](https://emacsformacos.com/emacs-builds/Emacs-pretest-26.1-rc1-1-universal.dmg), so it should not show the buggy behavior.

I'm going to mark this as fixed, if I missed something feel free to reopen.

**Comment by wyuenho** [comment]
Thank you!
