### ISSUE TITLE
changes to "set default font" menu item is not sticking

### ISSUE THREAD

**Issue by xdavidliu** [caldwell/build-emacs#72]
When using emacs on linux, I usually change the font to something larger and more readable by doing

M-(back tick) then D for "set default font", and finally M-(back tick) then o for "Save options".

This usually writes (custom-set-faces '(default ((t <etc etc> ...) to my .emacs file, where "..." includes the font family, size, etc,  and the font setting shows up correctly next time I reopen emacs. Note that custom-set-faces has an argument '(default ((t <etc etc> ...)

However, when using the prebuilt version on macos from emacsformacos.com, doing the above results in the font setting only sticking during that instance of emacs; when I close and reopen, the default setting comes back. Additionally, the (custom-set-faces) call written to .emacs has no argument at all.

I'm using the following:

GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911))
 of 2017-09-12

**Comment by caldwell** [comment]
This is probably not a build issue.
