### ISSUE TITLE
In emacs-pretest-26.1.91, arch-dependent data dir is wrong

### ISSUE THREAD

**Issue by paaguti** [caldwell/build-emacs#76]
I get the message

Warning: arch-dependent data dir '/Users/build/workspace/Emacs-Multi-Build/label/yosemite/emacs-source/nextstep/Emacs.app/Contents/MacOS/libexec/': No such file or directory when launching it from the CLI

Doesn't appear for Emacs 26.1

**Comment by caldwell** [comment]
This was due to a bad command line in Jenkins and should be fixed now.
