### ISSUE TITLE
Strange crash with certain buffers on macOS High Sierra V 10.13.4

### ISSUE THREAD

**Issue by acarlson99** [caldwell/build-emacs#80]
<img width="349" alt="Screen Shot 2019-07-10 at 3 20 23 PM" src="https://user-images.githubusercontent.com/34431218/61009058-47312a80-a326-11e9-9bee-810f0929c9ed.png">

As soon as I type the 'f' in ''if' it rejects any input, infinitely hanging until I force quit the application.  This only happens (to my knowledge) in c-mode, and does not happen in command line emacs.  I removed my config file and it still crashes without fail.

**Comment by caldwell** [comment]
This doesn't sound like a build problem. Launch with `/Applications/Emacs.app/Contents/MacOS/Emacs -Q` to bypass all startup scripts. If that fails on the most recent release or nightly version of Emacs then use `M-x report-emacs-bug` to let the Emacs maintainers know.
