### ISSUE TITLE
Fixing Build on macos Catalina

### ISSUE THREAD

**Issue by dgreatwood** [caldwell/build-emacs#88]
Running build on Catalina, we reach the predicted error:
```
  CC       xml.o
xml.c:23:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```

However, not sure how to proceed with the fix
`sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`
There is no Packages subfolder in /Library/Developer/CommandLineTools. There is no macOS_SDK_headers* file on the machine. According to various internet posts, Catalina does not include a headers package.

Is there some alternative change that would allow the build to proceed on Catalina?

BTW, the header files do seem to be expanded in the CommandLineTools folder.
Both these files exist:
```
./Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2/libxml/tree.h
./Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/libxml2/libxml/tree.h
```

With thanks!

**Comment by nloveladyallen** [comment]
This fixed it for me:

```
brew install libxml2
export LDFLAGS="-L/usr/local/opt/libxml2/lib"
export CPPFLAGS="-I/usr/local/opt/libxml2/include"
export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
```

**Comment by dgreatwood** [comment]
> This fixed it for me:
> 
> ```
> brew install libxml2
> export LDFLAGS="-L/usr/local/opt/libxml2/lib"
> export CPPFLAGS="-I/usr/local/opt/libxml2/include"
> export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
> ```
Confirmed - works for me as well, on Catalina 10.15.2

**Comment by hatch-carl** [comment]
You only need:
```
export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
```
