### ISSUE TITLE
MacOSX 10.11.6 "El Capitan" no longer supported?

### ISSUE THREAD

**Issue by Devon7** [caldwell/build-emacs#92]
If MacOSX 10.11.6 "El Capitan" is no longer supported, please post that news on the site.

		Peace
			--Devon

P.S.  It is true that the maintainers thoroughly broke redisplay, at least on my machine, with constant screen glitches and long pauses of blankness, but even if this was an upstream decision, it would be good to let folks know.

P.P.S.  Details follow:

	The following disk images couldn't be opened
	Image                                                                           	Reason
	Emacs-2020-04-11_01-40-26-aa072db86b6b06b54d7f5846231bdf4a73b0cd84-universal.dmg	no mountable file systems

  /Applications/Emacs-27.0.90.app/Contents/MacOS:
  total used in directory 22297
  -rwxr-xr-x  1 devon admin     3408 03-03 16:33 Emacs
  -rwxr-xr-x  1 devon admin  7399984 03-03 16:33 Emacs-x86_64-10_14
  -rw-r--r--  1 devon admin 15427064 03-03 14:27 Emacs.pdmp
  drwxr-xr-x  6 devon admin      204 03-03 16:33 bin-x86_64-10_14
  drwxr-xr-x 13 devon admin      442 03-03 16:33 lib-x86_64-10_14
  drwxr-xr-x  5 devon admin      170 03-03 16:33 libexec-x86_64-10_14

This application will not run on your computer. Sorry!

**Comment by yqrashawn** [comment]
Same thing happends on macos 10.13.6

**Comment by caldwell** [comment]
Sorry about that! I dropped support for 10.9 but neglected to add a build to take its place, so only 10.14 has been building. I added 10.10 in today, so nightlies going forward (starting from tonight's which hasn't built yet) and the 27.0.91-1 pretest (which has built) will support 10.10 - 10.15. I also added [a note on the site about it](https://emacsformacosx.com/about).

**Comment by Devon7** [comment]
Once again, thank you so much for all your efforts!

		Peace
			—Devon
