### ISSUE TITLE
No Notarised Binary For macOS

### ISSUE THREAD

**Issue by Ezirius** [caldwell/build-emacs#99]
**We need a notarised binary for macOS, please.**

This is very important in a era where security is and needs to be foremost in our minds. The lack of a notarised binary will deter people from trying the application and hinder adoption.

**Comment by ericpar** [comment]
I also vote for this "feature" as I can't use emacs due to security issues at my workplace.

**Comment by thynus** [comment]
Aren't the Universal Binaries on emacsforosx signed? Try:
codesign -dv --verbose=4 /Applications/Emacs.app

**Comment by jamesquilty** [comment]
I just updated from 28.2 (installed with `--no-quarantine` I believe) to 29.1 with Homebrew _without_ specifying `--no-quarantine` on macOS 13 and found that I can launch the app and run from the command line without error. I checked for notarisation as follows and everything seems to be OK:

```shell
$ spctl -a -t exec -v /Applications/Emacs.app
/Applications/Emacs.app: accepted
source=Notarized Developer ID

$ codesign -dvv /Applications/Emacs.app
...
Authority=Developer ID Application: Galvanix (5BRAQAFB8B)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
...
```

Perhaps this issue has been fixed?

**Comment by caldwell** [comment]
Yeah, it has. I initially intended to keep this open for a couple days just to make sure I had gotten it right and then of course promptly forgot. 🙂

According to the ["about" page](https://emacsformacosx.com/about) I did that a year ago. The Emacs-28.1-4 release was the first release to be notarized. Everything build after 2022-04-24 is notarized.
